### ISSUE TITLE
Error in `scripts/sequences-download.R` - possibly outdated domain in `scripts/load-libs.R`?

### ISSUE THREAD

**Issue by macrobiotus** [genner-lab/meta-fish-lib#26]
Dear developer(s),

I am encountering an error when stepping through the lower shell script described in the `README.md` of the project front page.

Specifically, the Bash call` scripts/sequences-download.R -q 500 -t 4 -e true` fails with error 
```Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: eutils.ncbi.nlm.nih.gov
```
Could this be due to an outdated domain in `scripts/load-libs.R `? This is the only place where I could so far find the web link to `"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&id="`.

I am attaching two screen shots and would look forward to your reply.

Kind regards,

Paul

![Screen Shot 2022-09-30 at 11 22 59](https://user-images.githubusercontent.com/10920135/193240896-0c4817c3-eae5-46fa-8575-51d52223b4dd.png)
**Fig. 1:** Error symptom

![Screen Shot 2022-09-30 at 11 23 09](https://user-images.githubusercontent.com/10920135/193240971-5ebd6b46-bbf5-4ec7-8b21-d3aa439535ea.png)
**Fig. 2:** Possible error cause

**Comment by boopsboops** [comment]
I think here, because the previous searches worked (i.e. report "Results returned for 4 batches"), then there is not a problem with the NCBI URL. In fact, if you insert a GI into the URL, it works as expected: [https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&id=NC_063705.1](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&id=NC_063705.1).

Unfortunately, because there are multiple simultaneous calls being made to the GenBank API, sometimes they fail, especially when the servers are busy or the connection breaks. It can be quite flaky sometimes, and it's difficult to know exactly what the problem is as often it at the NCBI end. Is it failing at the exact same point each time? 

Generally, the smaller the searches, the more of them there will be, and therefore a higher chance that once will fail. Maybe try doing slightly larger searches on fewer threads by adjusting the -q (size of search in characters) and -t (number of parallel threads) values. Perhaps run `scripts/sequences-download.R -q 1500 -t 2 -e false`.

I would definitely recommend testing the software completely with the provided test dataset before running with your own data, so to ensure that everything works on your machine. It runs very quickly, in less than 5 mins if you already have the R libraries installed. Code to test:

```bash
git clone https://github.com/genner-lab/meta-fish-lib.git meta-fish-lib-testing
cd meta-fish-lib-testing
mkdir -p reports temp/fasta-temp
echo 'ncbi.key <- "YOUR-NCBI-KEY"' > assets/ncbi-key.R
Rscript -e "renv::restore()"
scripts/check-genbank.R
cp assets/species-table-testing.csv assets/species-table.csv
scripts/sequences-download.R -q 1000 -t 2 -e false
scripts/references-assemble.R -t 2 -m all
scripts/qc.R -t 2 -v false
make -f scripts/Makefile
```

**Comment by macrobiotus** [comment]
Dear Rupert,
Thank you very much for your support and the notes on how to attempt progressing through the pipeline, I appreciate it. Will try and confirm once I have success. Kind regards, Paul Czechowski

**Comment by macrobiotus** [comment]
worked with `scripts/sequences-download.R -q 500 -t 1 -e true`
